from ex4_control_flow_helper import aight, ope

try:
    aight()
    aight()
    aight()
    aight()
    ope()
except:
    print('exception handled!')